from datetime import datetime

from sqlalchemy import func
from sqlalchemy.orm import Mapped, mapped_column, registry

table_registry = registry()


# https://fastapidozero.dunossauro.com/estavel/04/
@table_registry.mapped_as_dataclass
class User:
    __tablename__ = 'users'
    """
    Dataclass for User model.
        This class represents a user in the application with fields for
        username, password, email, and creation timestamp.
        The init field in mapped column is used to indicate that
        the field should not be included in the constructor.
        This is useful for fields that are automatically generated by
        the database, such as primary keys or timestamps.
    """

    id: Mapped[int] = mapped_column(init=False, primary_key=True)
    username: Mapped[str] = mapped_column(unique=True, index=True)
    password: Mapped[str]
    email: Mapped[str]
    created_at: Mapped[datetime] = mapped_column(
        init=False, server_default=func.now()
    )
